version: '3.9'
services:
    client:
        build:
            context: .
            dockerfile: ./.docker/Dockerfile
        restart: unless-stopped
        expose:
            - 80
        networks:
            - nginx-proxy

networks:
    nginx-proxy:
        external: true


# config for monorepo with multiple services

# version: '3.9'
# services:
#     client: 
#         build:  
#             context: .  
#             dockerfile: ./.docker/Dockerfile
#         restart: unless-stopped
#         expose:
#             - 80
#         networks:
#             - nginx-proxy
#     server:
#         build:
#             context: ./server
#             dockerfile: ./.docker/Dockerfile
#         restart: unless-stopped
#         expose:
#             - 5000
#         networks:
#             - nginx-proxy
#     db:
#         image: mongo:4.4.6
#         restart: unless-stopped
#         expose:
#             - 27017
#         networks:
#             - nginx-proxy 
#
# si x2 add 2nd reverse proxy, racine repo sans ssl qui a son .conf et qui redir sur /
# networks:
#     nginx-proxy:
#         external: true
