version: "3.9"
services:
  client:
    build:
      dockerfile: ./.docker/Dockerfile
    restart: unless-stopped
    # volumes:
    #   - ./src:/app/src
    networks:
      - nginx-proxy
      
networks:
  nginx-proxy:
    external: true