version: "3.9"
services:
  client: # can be named anything
    build:
      dockerfile: ./.docker/Dockerfile
    restart: unless-stopped
    expose:
      - 3000
    # volumes:
    #   - ./src:/app/src
    networks:
      - nginx-proxy
      
networks:
  nginx-proxy:
    external: true